const constants = {
  GET_COVID_STATS_FETCHING: 'GET_COVID_STATS_FETCHING',
  GET_COVID_STATS_SUCCESS: 'GET_COVID_STATS_SUCCESS',
  GET_COVID_STATS_ERROR: 'GET_COVID_STATS_ERROR',

  SELECTED_COUNTRY_SUCCESS: 'SELECTED_COUNTRY_SUCCESS',
  SELECTED_COUNTRY_ERROR: 'SELECTED_COUNTRY_ERROR',

  FILTER_COUNTRIES_HIGH_TO_LOW: 'FILTER_COUNTRIES_HIGH_TO_LOW',
  FILTER_COUNTRIES_LOW_TO_HIGH: 'FILTER_COUNTRIES_LOW_TO_HIGH',

  TRIGGER_MODAL: 'TRIGGER_MODAL'
}

export default constants
